### ISSUE TITLE
Error when creating circle from JSON file

### ISSUE THREAD

**Issue by muckee** [overlapmedia/imagemapper#1]
I'm creating interactive images in react.

Attempted to define a circle within the JSON file (tested and working with polygons):

```
{
  "id": "circle_1",
  "type": "circle",
  "data": [
    { "x": 60, "y": 60, "r": 60 }
  ]
}
```

I have also tried using the values `{ "cx": 60, "cy": 60, "r": 60 }` and  also replaced `"r"` with `"width"` and `"height"` attributes as I saw those referenced in the `Circle` definition.

No matter how I attempt to assign the values, when I reload the page and look at the console, I see the error messages:
`Unexpected value undefined parsing cx attribute.`
`Unexpected value undefined parsing cy attribute.`

What is the proper way to define a circle within the JSON file?

**Comment by croonerg** [comment]
Hello Joshua,

thanks for asking. The import function works best with exported data, but I definitely see a point in supporting a standardized format (eg. SVG coords). I will add that to the roadmap.

In the meantime, here are some examples of importing with current supported format. The format expects the bounding box of the shape which is formed by the four handles you drag when drawing and resizing rectangles, circles and ellipsis. Circles will center-align in the bounding box. X and Y is the starting point and width and height supports negative numbers to let you draw in any direction.

### Circle
```json
{
	"components": [{
		"id": "circle_1",
		"type": "circle",
		"data": {
			"x": 444,
			"y": 71,
			"width": 241,
			"height": 211
		}
	}]
}
```

### Rectangle
```json
{
	"components": [{
		"id": "rect_1",
		"type": "rect",
		"data": {
			"x": 253,
			"y": 51,
			"width": 324,
			"height": 197
		}
	}]
}
```

### Ellipse
```json
{
	"components": [{
		"id": "ellipse_1",
		"type": "ellipse",
		"data": {
			"x": 407,
			"y": 124,
			"width": 234,
			"height": 165
		}
	}]
}
```

### Polygon
```json
{
	"components": [{
		"id": "polygon_1",
		"type": "polygon",
		"data": [{
			"x": 603,
			"y": 114
		}, {
			"x": 625,
			"y": 203
		}, {
			"x": 699,
			"y": 124
		}]
	}]
}
```
