### ISSUE TITLE
Is it possible to add back a handle when drawing a polygon?

### ISSUE THREAD

**Issue by niniack** [overlapmedia/imagemapper#2]
In the demo, as I'm editing an existing polygon, I can move and delete handles (vertices), but there doesn't seem to be a way to add handles. Is that possible?

**Comment by croonerg** [comment]
Hello! Unfortunately you can't do it by user interaction. Programmatically you can do it with the Polygon's prototype method addPoint(x, y) which means you could extend the editor with this functionality yourself:

```javascript
editor.on('dblclick', (e) => {
  const polygon = editor.getComponentById("polygon_4");
  polygon.addPoint(e.offsetX, e.offsetY);
});
```
