### ISSUE TITLE
dinamically update image

### ISSUE THREAD

**Issue by simoneagostinelli** [overlapmedia/imagemapper#3]
Hi, 
I need to change image at runtime, I have a fileselector in my editor page, and I have to give the option to remove the image and upload another one. Is that possible?

**Comment by croonerg** [comment]
Hi,
if your image is added by using editor.loadImage(), you will need to delete or replace the image yourself by looking up
_.yourEditorId>image_ (or _svg>image_).

Another option is to create a SVG element with the image inside and connect the editor to it by giving the id when instantiating a new Editor, ref. the "svgEl" param [here](https://overlapmedia.github.io/imagemapper/docs/classes/Editor.html#constructor).
This means you could have image handling (adding, deleting, replacing or whatever you want) outside the imagemapper library.

**Comment by simoneagostinelli** [comment]
Thank you very much! your solution works fine!
