### ISSUE TITLE
off() event

### ISSUE THREAD

**Issue by christianrockbryan** [overlapmedia/imagemapper#4]
Can you please give an example how to call the off() event?  I need to call a function when someone deletes a shape and I've tried many different ways and none work.

Thanks,
Bryan

**Comment by croonerg** [comment]
Hello Bryan,

off() is to remove event listeners and is used by eg. `editor.off('click', methodRef);`

I realised there's no editor handler to catch deletion events, but there's a workaround:
```javascript
myEditor.fsmService.onTransition((state) => {
    if (state.actions.some((action) => action.type === 'deleteComponent')) {
        const elementDeleted = state.context.mouseDownInSelectModeObject.element;
        console.log('Element is deleted', elementDeleted.id);
    }
});
```

**Comment by christianrockbryan** [comment]
That worked great.  Thank you!

At 01:44 PM 5/14/2023, you wrote:
