### ISSUE TITLE
Unable to Zoom

### ISSUE THREAD

**Issue by asad-jeevaysoft** [overlapmedia/imagemapper#5]
Hi .. Is it possible to zoom image while using this Package.

**Comment by croonerg** [comment]
Hi,
View Tools (like zoom) is not something this library aims to cover. In most cases (if not all), you will have full control over the image you are using with the lib.

Here's a simple example: [https://codepen.io/overlapmedia/pen/mdvZvRW](https://codepen.io/overlapmedia/pen/mdvZvRW)
