### ISSUE TITLE
Any plans for Typescript support and examples?

### ISSUE THREAD

**Issue by ralvs** [overlapmedia/imagemapper#6]

**Comment by croonerg** [comment]
Yes, it's [WIP on develop](https://github.com/overlapmedia/imagemapper/commit/2de4288f44f7b08f9d7aa4ecf8ad16f149d9b696).

**Comment by ArveWaltin** [comment]
Newest release has Typescript support.

**Comment by croonerg** [comment]
Newest release has Typescript support.
