### ISSUE TITLE
Warning from XState in browser console

### ISSUE THREAD

**Issue by ralvs** [overlapmedia/imagemapper#8]
Hello guys,

I'm getting this warning when instantiating the 'editor'

> ImageMapperEditor.js:33 It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html

**Comment by croonerg** [comment]
It will be fixed by the [XState migration](https://github.com/overlapmedia/imagemapper/commit/96d9999146855119c5f842a3d501f31db8ded863).

**Comment by croonerg** [comment]
Should be fixed now.
