### ISSUE TITLE
Import multiple polygons with different colors in the View mode

### ISSUE THREAD

**Issue by ralvs** [overlapmedia/imagemapper#9]
Hello again.

My use case for this library is to mark different land spaces in a map and each property has a status (sold, available, negotiation).
I need to import these polygons with different colors to show the status.

Please, how can I do that?

<img width="445" alt="Screenshot 2023-12-30 at 10 41 14 AM" src="https://github.com/overlapmedia/imagemapper/assets/5287233/90a2eb43-322d-4fed-8e4a-7edb349b78e8">

**Comment by croonerg** [comment]
Hello! You could style imported components like so:

```javascript
const importedComponents = myView.import(
  '{"idCounter":4,"components":[{"id":"rect_1","type":"rect","data":{"x":66,"y":36,"width":253,"height":148}},{"id":"polygon_2","type":"polygon","data":[{"x":376,"y":172},{"x":498,"y":291},{"x":625,"y":174},{"x":500,"y":57}]},{"id":"polygon_3","type":"polygon","data":[{"x":54,"y":249},{"x":234,"y":246},{"x":236,"y":225},{"x":415,"y":270},{"x":237,"y":313},{"x":235,"y":294},{"x":54,"y":292}]}]}',
);

importedComponents.forEach((c) =>
  c.setStyle({
    ...c.style,
    component: {
      ...c.style.component,
      fill: 'rgb(255, 0, 0)',
    },
  }),
);
```

**Comment by ralvs** [comment]
That's great @croonerg 
I will try that. 

Before, I have tried the approach of adding style to the import string. 

https://github.com/ralvs/imagemapper/commit/6c37a22895694c48ef6d5724a2d349b416639b1e
